name: Feature CI
on:
  pull_request:
    branches: [ develop ]
    types: [labeled, synchronize]
jobs:
  runCI:
    if: >-
      (github.event.action == 'labeled' && github.event.label.name == 'ready') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'ready'))
    runs-on: ubuntu-latest
    steps:
      - name: Run feature branch CI
        run: |
          ${{ github.event.INSERT_HERE }}
          BODY=
          BODY=$BODY'{'
          BODY=$BODY'   "hook_info":{'
          BODY=$BODY'      "type":"bitrise",'
          BODY=$BODY'      "build_trigger_token":"0gPjv5gqLVo5s1gx5IFdJw"'
          BODY=$BODY'   },'
          BODY=$BODY'   "build_params":{'
          BODY=$BODY'      "base_repository_url":"${{ github.event.repository.ssh_url }}",'
          BODY=$BODY'      "branch":"${{ github.event.pull_request.head.ref }}",'
          BODY=$BODY'      "branch_dest":"${{ github.event.pull_request.base.ref }}",'
          BODY=$BODY'      "branch_dest_repo_owner":"${{ github.event.pull_request.base.repo.owner.login }}",'
          BODY=$BODY'      "branch_repo_owner":"${{ github.event.pull_request.head.repo.owner.login }}",'
          BODY=$BODY'      "commit_hash":"${{ github.event.pull_request.head.sha }}",'
          #BODY=$BODY'      "commit_message":"[#180868363] Added special case to fix ICU's library bug for DKK curr…\n\n**Business Context:**\nSomething not working well with how we translate currency abbreviation into a symbol.\n\nAlso on the carousel we aren't seeing the correct currency symbol. For this version of Android we see DKK when changing to denmark.\n\n**Pivotal Link:** https://www.pivotaltracker.com/story/show/180868363\n\n---\n…ency code",'
          #BODY=$BODY'      "commit_paths":null,'
          BODY=$BODY'      "diff_url":"${{ github.event.pull_request.diff_url }}",'
          #BODY=$BODY'      "environments":['
          #BODY=$BODY'         {'
          #BODY=$BODY'            "value":"1547",'
          #BODY=$BODY'            "key":"SOURCE_BITRISE_BUILD_NUMBER"'
          #BODY=$BODY'         }'
          #BODY=$BODY'      ],'
          BODY=$BODY'      "head_repository_url":"${{ github.event.pull_request.head.repo.ssh_url }}",'
          BODY=$BODY'      "pull_request_author":"${{ github.event.pull_request.user.login }}",'
          BODY=$BODY'      "pull_request_head_branch":"pull/${{ github.event.pull_request.number }}/head",'
          BODY=$BODY'      "pull_request_id":${{ github.event.pull_request.number }},'
          BODY=$BODY'      "pull_request_merge_branch":"pull/${{ github.event.pull_request.number }}/merge",'
          BODY=$BODY'      "pull_request_repository_url":"${{ github.event.pull_request.base.repo.ssh_url }}",'
          BODY=$BODY'      "skip_git_status_report":true,'
          BODY=$BODY'      "workflow_id":"feature"'
          BODY=$BODY'   },'
          BODY=$BODY'   "triggered_by":"curl"'
          BODY=$BODY'}'
          echo "BODY: ${BODY}"
          curl \
            --data "${BODY}" \
            https://app.bitrise.io/app/75d16fae86cc3924/build/start.json 
